pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "approved-reviews-by>=1"
      - "check-success=Semantic Pull Request"
      - "check-success=linter"
      - "check-success=terraform:generic"
      - "check-success=terraform:aws"
      - "check-success=terraform:scaleway"
    actions:
      merge:
        method: merge
