pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=main
    actions:
      merge:
        method: squash
  - name: Automatic merge on approval release
    conditions:
      - base=release
    actions:
      merge:
        method: merge
